### ISSUE TITLE
现在请求数据出现了乱码

### ISSUE THREAD

**Issue by linjinghui01** [LoadChange/amemv-crawler#10]

**Comment by LoadChange** [comment]
你搜得太多啦，让服务器宝宝休息一下吧～

**Comment by LoadChange** [comment]
这是我刚才查看结果时 收到的返回，我账号的cookie使用的人太多了，请用自己帐号下载视频把，登录app之后抓个包，把cookie 写到程序的cookie.txt文件中就可以咯

**Comment by linjinghui01** [comment]
兄弟  我自己抓的cookie昨天下午开始显示是乱码

**Comment by linjinghui01** [comment]
我用的自己的

**Comment by LoadChange** [comment]
我测试了一下，挺正常的，方便说一下的你关键词吗？或者你把第25 行注释 试试
# f.write('\r\n' + title + '\r\n')

**Comment by linjinghui01** [comment]
提两个问题:


1.我换了台机器正常截包，刚开始可以，几分钟cookile又开始乱码  

2.用正常的cookie去运行昨天的脚本，报这个错。 但是我看字段有好像没问题    

![1](https://user-images.githubusercontent.com/12868663/38850247-26fffb0a-4243-11e8-86f1-e3938714c5e5.png)

**Comment by LoadChange** [comment]
好的，晚点我跟一下这个问题，但是看你的报错已经进入get_aweme_list函数了，这里已经里app了，是不需要cookie的，可能和_signature有关

**Comment by linjinghui01** [comment]
方便加下你qq或者微信吗，也方便跟您交流

**Comment by LoadChange** [comment]
好的  你说

**Comment by linjinghui01** [comment]
我的qq号1554896963 微信linjinghui007
