### ISSUE TITLE
好像抖音那边改了东西？

### ISSUE THREAD

**Issue by sherlockwhite** [loadchange/amemv-crawler#100]
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.iesdouyin.com', port=443): Max retries exceeded with url: /aweme/v1/aweme/post/?user_id=58865791120&count=21&max_cursor=0&aid=1128&_signature=CBt1qAAAVCX35IpX7YtURwgbdb%0A&dytk=9b9e00904fcc3c36aca3dc267ca86a42 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))

**Comment by loadchange** [comment]
短连接发一下

**Comment by sherlockwhite** [comment]
> 短连接发一下
又没啥问题了
