### ISSUE TITLE
代码是不是没有用了？？

### ISSUE THREAD

**Issue by double1991** [loadchange/amemv-crawler#101]
代码是不是没有用了？？我这边把你代码运行就错了，加密的地方好像获取不到什么数据

**Comment by thenick113** [comment]
貌似是失效了

**Comment by loadchange** [comment]
哪个失效了？发短连接吧

**Comment by double1991** [comment]
> 哪个失效了？发短连接吧

大神，我是直接运行你提供的代码，直接运行就报错了，p = os.popen('node fuck-byted-acrawler.js %s' % value)
        return p.readlines()[0]

代码是这个地方获取签名的地方直接数组越界了

**Comment by loadchange** [comment]
> > 哪个失效了？发短连接吧
> 
> 大神，我是直接运行你提供的代码，直接运行就报错了，p = os.popen('node fuck-byted-acrawler.js %s' % value)
> return p.readlines()[0]
> 
> 代码是这个地方获取签名的地方直接数组越界了

没装node？

**Comment by thenick113** [comment]
今天重新试了一下，可以用。

**Comment by loadchange** [comment]
> 我从抖音随便复制了几个链接都用不了。
> http://v.douyin.com/NTwNXf/,
> http://v.douyin.com/Nw8y7q/,
> http://v.douyin.com/NwYqCU/,
> http://v.douyin.com/NwkooQ/,
> http://v.douyin.com/NwAfXL/,
> http://v.douyin.com/Nw8S5n/,
> http://v.douyin.com/NwkKY8/,
> http://v.douyin.com/NwrNhL/,
> http://v.douyin.com/NwL5Cr/,
> http://v.douyin.com/Nwjkj9/
> 运行之后什么都没下载就结束了

你这些都是单视频啊。。。。麻烦看下readme

**Comment by thenick113** [comment]
可以用了，之前理解错误了，这个还是很方便的
