### ISSUE TITLE
ios和android提取用户信息不同

### ISSUE THREAD

**Issue by ariagecheney** [loadchange/amemv-crawler#104]
ios使用抖音 提取出来的是http://v.douyin.com/FEe9Ao/
而android提取的是http://www.iesdouyin.com/share/user/74767852886?u_code=19d2l4j24/?share_type=link&from=singlemessage
 ios成功，而android失败。
将from=singlemessage删除后 ，依然失败。

**Comment by loadchange** [comment]
![wx20190209-141204](https://user-images.githubusercontent.com/10842824/52517323-c38ae900-2c74-11e9-99ae-96b06801261c.png)

没发现什么问题
