### ISSUE TITLE
如何让程序跑起来--这个问题比较low

### ISSUE THREAD

**Issue by mengdaya** [loadchange/amemv-crawler#108]
如何让程序跑起来，出现如下错误
![image](https://user-images.githubusercontent.com/17229080/53320643-2cc75900-3911-11e9-90b1-1b64c0b7397d.png)

**Comment by mengdaya** [comment]
IndexError: list index out of range

**Comment by mengdaya** [comment]
![image](https://user-images.githubusercontent.com/17229080/53321080-706e9280-3912-11e9-9eae-b97e326b6a09.png)

**Comment by loadchange** [comment]
安装node
