### ISSUE TITLE
#挑战的接口是不是也变了

### ISSUE THREAD

**Issue by taojian1989** [LoadChange/amemv-crawler#11]
challenge_info = self._search(challenge, 'challenge')
这里每次获取的为None了

**Comment by LoadChange** [comment]
要用自己的cookie哦

**Comment by LoadChange** [comment]
版本上的cookie 只是个演示，用的人太多，我已经退出了

**Comment by visense** [comment]
> challenge_info = self._search(challenge, 'challenge')
> 这里每次获取的为None了

挑战怎么用
