### ISSUE TITLE
How do we crawl from tiktok global?

### ISSUE THREAD

**Issue by seanphan** [loadchange/amemv-crawler#113]
Thank you for sharing this project. This works really great with douyin.com domains. How can we crawl from the global URL such as: https://www.tiktok.com/share/user/6640433256620261381?refer=pc_reflow_trending&langCountry=en

**Comment by Carlosx7** [comment]
I had same mistake, I found all tiktok user did not download, as dytk cannot recive the value then brake the program.

**Comment by seanphan** [comment]
Works great. Thank you @loadchange

**Comment by seanphan** [comment]
hi @loadchange , I think this issue happens again. I'm no longer able to download from the global link
