### ISSUE TITLE
国际版抖音怎么下载个人主页，不附带下载个人喜欢

### ISSUE THREAD

**Issue by a7832175** [loadchange/amemv-crawler#114]
大神你好,
国际版抖音批量解析的时候会附带下载主页的个人喜欢
如果不想下载个人喜欢，只想下载主页作品，怎么做那？
希望大神看到，感谢大神。

**Comment by ssl199305** [comment]
把代码中
 favorite_folder = target_folder + '/favorite'
            video_count = self.__download_favorite_media(
                user_id, dytk, hostname, signature, favorite_folder, video_count)
删掉

**Comment by a7832175** [comment]
> 把代码中
> favorite_folder = target_folder + '/favorite'
> video_count = self.__download_favorite_media(
> user_id, dytk, hostname, signature, favorite_folder, video_count)
> 删掉

搞定了，感谢大神

**Comment by lbcake** [comment]
> > 把代码中
> > favorite_folder = target_folder + '/favorite'
> > video_count = self.__download_favorite_media(
> > user_id, dytk, hostname, signature, favorite_folder, video_count)
> > 删掉
> 
> 搞定了，感谢大神

没看懂 请问 能来个联系方式吗？ 求教

**Comment by lbcake** [comment]
> 把代码中
> favorite_folder = target_folder + '/favorite'
> video_count = self.__download_favorite_media(
> user_id, dytk, hostname, signature, favorite_folder, video_count)
> 删掉

大神 你好 现在tik tok  不是已经被墙了吗？ 完全看不了 这个能直接下？ 不用设置代理 或者飞机什么的吗？

**Comment by a7832175** [comment]
> > > 把代码中收藏夹=目标文件夹+‘/收藏’视频计数=Self._下载_收藏媒体(用户_id，dytk，主机名，签名，收藏夹，视频_计数)删掉
> > 
> > 
> > 搞定了，感谢大神
> 
> 没看懂请问能来个联系方式吗？求教
编辑amemv-video-ripper.py
把favorite_folder = target_folder + '/favorite'
video_count = self.__download_favorite_media(
user_id, dytk, hostname, signature, favorite_folder, video_count)
删掉就可以了

**Comment by lbcake** [comment]
> > > > 把代码中收藏夹=目标文件夹+‘/收藏’视频计数=Self._下载_收藏媒体(用户_id，dytk，主机名，签名，收藏夹，视频_计数)删掉
> > > 
> > > 
> > > 搞定了，感谢大神
> > 
> > 
> > 没看懂请问能来个联系方式吗？求教
> > 编辑amemv-video-ripper.py
> > 把favorite_folder = target_folder + '/favorite'
> > video_count = self.__download_favorite_media(
> > user_id, dytk, hostname, signature, favorite_folder, video_count)
> > 删掉就可以了

现在国际版tik tok  能下载吗？  貌似被墙了

**Comment by a7832175** [comment]
> > > > > 把代码中收藏夹=目标文件夹+‘/收藏’视频计数=Self._下载_收藏媒体(用户_id，dytk，主机名，签名，收藏夹，视频_计数)删掉
> > > > 
> > > > 
> > > > 搞定了，感谢大神
> > > 
> > > 
> > > 没看懂请问能来个联系方式吗？求教
> > > 编辑amemv-video-ripper.py
> > > 把favorite_folder = target_folder + '/favorite'
> > > video_count = self.__download_favorite_media(
> > > user_id, dytk, hostname, signature, favorite_folder, video_count)
> > > 删掉就可以了
> 
> 现在国际版tik tok 能下载吗？ 貌似被墙了

国际版下载需要翻墙

**Comment by lbcake** [comment]
> > > > > > 把代码中收藏夹=目标文件夹+‘/收藏’视频计数=Self._下载_收藏媒体(用户_id，dytk，主机名，签名，收藏夹，视频_计数)删掉
> > > > > 
> > > > > 
> > > > > 搞定了，感谢大神
> > > > 
> > > > 
> > > > 没看懂请问能来个联系方式吗？求教
> > > > 编辑amemv-video-ripper.py
> > > > 把favorite_folder = target_folder + '/favorite'
> > > > video_count = self.__download_favorite_media(
> > > > user_id, dytk, hostname, signature, favorite_folder, video_count)
> > > > 删掉就可以了
> > 
> > 
> > 现在国际版tik tok 能下载吗？ 貌似被墙了
> 
> 国际版下载需要翻墙

我已经翻了 不管是全局 还是PAC都不行， 还是不能下载  不只是什么情况    难道代码 还需要自己变更吗？   还是 执行py的时候 要单加语句

**Comment by loadchange** [comment]
#85

**Comment by lbcake** [comment]
> #85

请问 国际版 怎么搞定下载啊？ 我这里有稳定的国外服务器

**Comment by seanphan** [comment]
`python3 amemv-video-ripper --no-favorite` to download without favorite.

I hardcoded this part in order to download from global link:

`
is_global = True
if is_global:
	download_url = 'http://api.tiktokv.com/aweme/v1/play/?{0}'
`
@lbcake

**Comment by lbcake** [comment]
> `python3 amemv-video-ripper --no-favorite` to download without favorite.
> 
> I hardcoded this part in order to download from global link:
> 
> ```
> is_global = True
> if is_global:
> 	download_url = 'http://api.tiktokv.com/aweme/v1/play/?{0}'
> ```
> @lbcake

不下载喜欢的我 搞定了， ，  但是 国际版怎么下载呢？ 我这边不知道为何 开代理也不能下
