### ISSUE TITLE
老是提醒抖音号不存在

### ISSUE THREAD

**Issue by crazyjudas** [LoadChange/amemv-crawler#12]

**Comment by LoadChange** [comment]
要用自己的cookie哦

**Comment by crazyjudas** [comment]
我使用了自己在douyin.com的cookie也不可以，请问一下，倒地是用哪个cookie呢

**Comment by LoadChange** [comment]
观察URL:https://api.amemv.com/aweme/v1/*/search/?

**Comment by LoadChange** [comment]
需要登录app

**Comment by crazyjudas** [comment]
登录了app, 打开链接是{"message": "Url does not match", "extra": {"logid": "20180417174046010011050100093861", "now": 1523958046102, "fatal_item_ids": []}}
