### ISSUE TITLE
万人血书求快手、微视的批量视频Python啊

### ISSUE THREAD

**Issue by weigongcheng** [loadchange/amemv-crawler#123]
老哥，已打赏，素质三连了，万人血书求快手、微视的批量视频Python啊

**Comment by lbcake** [comment]
> 老哥，已打赏，素质三连了，万人血书求快手、微视的批量视频Python啊

你用这个下抖音  最多单次命令 能下多少？ 下三四千个就断了吧

**Comment by weigongcheng** [comment]
我是一个个来下的，

**Comment by lbcake** [comment]
> 我是一个个来下的，

抖音 你也一个一个下？？？

**Comment by chenglinfeng** [comment]
同求快手同一用户批量视频下载，github上大部分代码api已失效
