### ISSUE TITLE
获取signature失败了

### ISSUE THREAD

**Issue by yuuiki** [loadchange/amemv-crawler#131]
你好，我在windows上运行的，报错了IndexError: list index out of range，我对js不是很熟悉，可以帮忙看看原因吗
![image](https://user-images.githubusercontent.com/29880212/57682430-6b44f800-7664-11e9-9e9a-c698ab17d379.png)

**Comment by missedMahattanhenge** [comment]
你应该是没安装nodejs

**Comment by missedMahattanhenge** [comment]
> 你好，我在windows上运行的，报错了IndexError: list index out of range，我对js不是很熟悉，可以帮忙看看原因吗
> ![image](https://user-images.githubusercontent.com/29880212/57682430-6b44f800-7664-11e9-9e9a-c698ab17d379.png)


你应该是没安装nodejs

**Comment by loadchange** [comment]
@missedMahattanhenge 说的对，安装node应该就可以了
