### ISSUE TITLE
致作者：有人把你这程序用于商业用途和欺诈

### ISSUE THREAD

**Issue by yzxian** [loadchange/amemv-crawler#135]
昨天我在找批量下载抖音视频的程序，发现有人售卖源码，我买过来后发现是来自github的项目，并且他在卖之前还骗我说有java版的，结果最后只能给python版的。从他给我的记录来看，他卖了很久了，没一套100元。如果作者需要了解详情，请联系我。

**Comment by loadchange** [comment]
感谢反馈，我会关注的
