### ISSUE TITLE
How to download single video?

### ISSUE THREAD

**Issue by nghiepit** [loadchange/amemv-crawler#154]
Hi guys,

I just want to download the single video.
Example URL: `http://vt.tiktok.com/JaUxFm/`

Thank you in advance.

**Comment by qq609100037** [comment]
Can you download video by topic？

**Comment by nghiepit** [comment]
Yes, I can

**Comment by zzpop** [comment]
https://v19.muscdn.com/3f645c8701b5a41ee8f45b5ecd79eaff/5d339339/video/tos/maliva/tos-maliva-v-0000/dc158e3ca78542c49f2bf7b7dda14baf/?rc=amhtNGY0eXdmbTMzOTw7M0ApQHRwbndsQG9FMzU0PDMzNDMzNTQ0NTM0NW9AaDZ2KUBnM3cpQGYzdSlmc2V6aGhkZjY1QDRebGg2cl5lYV8tLV4wNnNzNW8jXGxocW8jQTQzLi4zMi4uMzUzLTQ2LTojbyM6YS1vIzpgLXAjOmBoXitiK2p0OiMwLl4%3D

**Comment by nghiepit** [comment]
@zzpop I can't access your URL, maybe it expired. Can you share how do it?
