### ISSUE TITLE
现在视频无法下载了

### ISSUE THREAD

**Issue by jhao104** [loadchange/amemv-crawler#162]
![TIM图片20190924164321](https://user-images.githubusercontent.com/15058920/65496117-79e0cd00-deea-11e9-8597-f22896dc9265.png)

**Comment by jhao104** [comment]
是抖音抽疯， `aweme.snssdk.com` 有时候下不了

**Comment by cnscorpions** [comment]
嗯，其他的库存倒是可以下的

[Gmail 编程邮箱 - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=6coo8)	[6coo8]

On September 25, 2019 at 3:08 GMT, J hao104 <notifications@github.com> wrote:

是抖音抽疯， aweme.snssdk.com 有时候下不了

**Comment by EnvoySir** [comment]
> 可以的，作者在share-url.txt的地址都删除掉，换上自己的就行

我下载下来的大小为0字节什么鬼
