### ISSUE TITLE
spider based on douyin id

### ISSUE THREAD

**Issue by eeezae** [LoadChange/amemv-crawler#18]
系统给的id不能用来抓取了吗，怎么感觉现在像是通过分享动态生成一个非常短时效的id从接口来拿数据

**Comment by eeezae** [comment]
如果我必须要用系统给的id来拿数据的话，大佬有有什么建议的思路吗？是否可以根据这个id来获得分享生成的url呢

**Comment by LoadChange** [comment]
分享链接带的id才是真实的id，不是短时效的，原来的方式我还是走了搜索接口去拿这个真实id，app的接口涉及到mas算法的问题，以前可以用是他们搜索并没有验证这个mas值，现在这条路已经被堵死了，我们没办法计算这个值，所以就直接拿分享连接就好了

**Comment by eeezae** [comment]
万分感谢🙏大佬你的帮助，等项目提交成功后请你喝咖啡🍵。不过求抖音别再修改反爬政策了5555

**Comment by eeezae** [comment]
P.S. 大佬你以前的_search()方法我刚刚经过的测试又可以用了，你可以把代码回拉一下看看用number可不可以跑

**Comment by LoadChange** [comment]
好的，谢谢提醒😉
