### ISSUE TITLE
get_dytk 是不是已经获取不到了？

### ISSUE THREAD

**Issue by SuperDoraemon** [loadchange/amemv-crawler#188]
error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 5: invalid start byte

**Comment by xmtrockET** [comment]
dytk好像不是必要参数了。我试了现在用sec_uid能拿个人信息，同样也是要sec_uid能拿视频列表，不需要dytk也成。

**Comment by SuperDoraemon** [comment]
> error:
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 5: invalid start byte

**Comment by SuperDoraemon** [comment]
> error:
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 5: invalid start byte
