### ISSUE TITLE
怎么能爬到抖音号？

### ISSUE THREAD

**Issue by shuitai** [LoadChange/amemv-crawler#2]
怎么能爬到抖音号？

**Comment by LoadChange** [comment]
额一般人没这个需求吧，我没太考虑这方面，因为抖音还是脑残多的，好的视频，也只有在正常人的帐号里，如果你想无目的的爬取，就只能刷推荐流了

**Comment by shuitai** [comment]
因为你的开源代码需要设定好抖音号，当我不知道抖音号，就爬不到了吧，那请问推荐流该怎么爬取？

**Comment by LoadChange** [comment]
https://api.amemv.com/aweme/v1/feed  具体参数抓个包吧，一直刷这个接口就可以了，这样的话也就没必要知道抖音号了，直接下feed流里的视频就可以了，但是感觉意义不大，项目dev分支 支持了challenge下载可以试试。
