### ISSUE TITLE
怎么把视频下载的名字改了？

### ISSUE THREAD

**Issue by huoyanrenzhe** [loadchange/amemv-crawler#22]
怎么把视频下载的名字改了？
想改成 原生的视频名字+用户名

目前的方式有点难区别视频内容。

**Comment by 1990754123** [comment]
自己根据json，自己定义几个变量即可。。
如果你会写代码的话。

**Comment by kxltsuper** [comment]
这个问题搞定了吗？确实还有带有原生标题更直观。
