### ISSUE TITLE
video url无法爬取

### ISSUE THREAD

**Issue by void-main** [LoadChange/amemv-crawler#24]
类似这种url无法获取：

https://www.iesdouyin.com/share/video/6552866489014160647/?region=CN&mid=6534425933733071620&titleType=title&timestamp=1525735944

是需要额外的解析方法么？

**Comment by LoadChange** [comment]
没做单个视频的处理，只支持用户、挑战、音乐的爬取，单个视频的话，在浏览器点击一下播放按钮，审查一下视频元素，有一个video标签src复制到地址栏就可以下载了
