### ISSUE TITLE
能爬取视频属性信息吗？

### ISSUE THREAD

**Issue by LukeHe** [LoadChange/amemv-crawler#26]
请问能够爬取视频属性信息吗？比如什么时候发布的，视频宽度和高度，点赞数，评论数，播放数这些

**Comment by LoadChange** [comment]
发布时间 播放数 分享数 这些应该是有的

**Comment by buptbf** [comment]
> 请问能够爬取视频属性信息吗？比如什么时候发布的，视频宽度和高度，点赞数，评论数，播放数这些

你实现视频属性的爬取了吗？
