### ISSUE TITLE
视频的评论怎么抓取，加密的as、cp、mas如何获取可有办法？感谢！

### ISSUE THREAD

**Issue by IanChenBJ** [LoadChange/amemv-crawler#29]

**Comment by LoadChange** [comment]
抱歉，这个我也没思路

**Comment by laughmaker** [comment]
def _generate_as_cp(self):
        t = int(round(time.time(), 3))
        i = hex(t)[2:].upper()
        hash = hashlib.md5()
        hash.update(str(t).encode('utf-8'))
        e = hash.hexdigest().upper()
        if len(i) != 8:
            return '479BB4B7254C150', '7E0AC8874BB0985'
        s = e[:5]
        o = e[-5:]
        n = ''
        for a in range(5):
            n += s[a] + i[a]
        l = ''
        for r in range(5):
            l += i[r + 3] + o[r]
        as_ = 'A1' + n + i[-3:]
        cp = i[:3] + l + "E1"
        return as_, cp

    def _mas(self):
        part = hashlib.sha224(str(time.time()).encode()).hexdigest()
        return part[:50]

从网上找到的，正在测试
