### ISSUE TITLE
能增加一个按照主题或话题的下载方法吗？

### ISSUE THREAD

**Issue by cachenow** [LoadChange/amemv-crawler#3]
如题

**Comment by LoadChange** [comment]
已经在dev分支中支持该功能😏，我还没太仔细的测试，文档也没写😉，暂时先不合过来了🚗🚗🚗，可以拉取dev分支代码尝尝💀，不要在终端中直接写主题名称，请在user-number.txt中添加需要下载的主题，目前只对关键词搜索后的第一个challenge下载，不支持选择🛀

**Comment by LoadChange** [comment]
已经在dev分支中支持该功能😏，我还没太仔细的测试，文档也没写😉，暂时先不合过来了🚗🚗🚗，可以拉取dev分支代码尝尝💀，不要在终端中直接写主题名称，请在user-number.txt中添加需要下载的主题，目前只对关键词搜索后的第一个challenge下载，不支持选择🛀

**Comment by hzc54188** [comment]
厚着脸皮请大大帮忙看一下
![33](https://user-images.githubusercontent.com/24639554/38407793-79111436-39ad-11e8-8cc1-70e0fdf68701.png)

**Comment by LoadChange** [comment]
😓，编码有问题，更新试试，改成二进制读了，手边没有windows机器测不了

**Comment by hzc54188** [comment]
@LoadChange 手动改成ansi编码已经解决问题了呢，如题能增加一个按照音乐的下载方法码？

**Comment by hzc54188** [comment]
@cachenow 基友去试试dev版本哟，按音乐的下载方法正在添加中...

**Comment by visense** [comment]
> 已经在dev分支中支持该功能😏，我还没太仔细的测试，文档也没写😉，暂时先不合过来了🚗🚗🚗，可以拉取dev分支代码尝尝💀，不要在终端中直接写主题名称，请在user-number.txt中添加需要下载的主题，目前只对关键词搜索后的第一个challenge下载，不支持选择🛀

dev分支在哪下？
