### ISSUE TITLE
不能下载视频的图片

### ISSUE THREAD

**Issue by lyj9768** [LoadChange/amemv-crawler#30]
视频可以正常下载，但是下载不到图片呀

**Comment by LoadChange** [comment]
请把你的链接发一下

**Comment by lyj9768** [comment]
https://www.douyin.com/share/user/6556303280?share_type=link&tt_from=weixin&utm_source=weixin&utm_medium=aweme_ios&utm_campaign=client_share&uid=97193379950&did=30337873848

我用的是这个你自带的链接
全部都没有图片

**Comment by LoadChange** [comment]
额，我把程序跑了一遍，并没有图片啊，难道你是说视频的关键帧图片？

**Comment by lyj9768** [comment]
我看代码说明说增加了图片下载嘛，我以为可以下载视频的封面。。

**Comment by lyj9768** [comment]
简单的说就是可以下载视频的时候顺带下载一下视频的封面么

**Comment by kxltsuper** [comment]
@看代码时我也有这个疑问，不知道下载图片这个功能是什么意思

**Comment by LoadChange** [comment]
哈哈哈哈哈，了解；是这样的，那个图片并不是关键帧的图片，而且是用户就发了一个图片，抖音应该是有这个的功能的，可以翻一下，前面有一个issue，当时他给我留了一个用户id，说下载会报错，我后来发现就是这个用户列表下面不光有视频，居然还有图片，代码里的下载图片功能是指这个，但是很少有用户发图片，这个还挺难找的，如果你们想取关键帧，只需要看一下接口就好了，这个很好下载到。
