### ISSUE TITLE
_signature错误

### ISSUE THREAD

**Issue by chaopengz** [LoadChange/amemv-crawler#31]
Hi，我在爬用户信息时的也遇到了_signature字段，但是用fuck-byted-acrawler.js拿到的signature却用不了，请问下是怎么回事呢？
用户url: https://www.douyin.com/share/user/2613650662
抓数据的url: https://www.douyin.com/aweme/v1/aweme/post/?user_id=2613650662&count=21&max_cursor=0&aid=1128&_signature=vsISThAa5eS8bwWIdK-OVL7CEl
_signature生成的js: https://s3a.bytecdn.cn/ies/resource/falcon/douyin_falcon/pkg/third_ee38eac.js 里的/*!douyin_falcon:node_modules/byted-acrawler/dist/runtime.js*/
感谢！～

**Comment by LoadChange** [comment]
#14
