### ISSUE TITLE
请问一下为啥抖音里面明明有视频 但爬取的时候打印的是video number 0

### ISSUE THREAD

**Issue by zthaa** [loadchange/amemv-crawler#33]
就像这样：
There's no video in number 89923118343.

Aweme number 89923118343, video number 0

**Comment by LoadChange** [comment]
检查一下你的环境

**Comment by zthaa** [comment]
是这样的   我在share-url.txt 里面放了100多个链接 ，开始有的能下载视频，到后面都变成video number 0

**Comment by LoadChange** [comment]
这么多。。。。。。我没做过这样的测试，我猜可能触发一些后端的边界保护。把你的100多个链接贴一下，我有时间试试吧~~

**Comment by zthaa** [comment]
http://www.douyin.com/share/user/89923222175?
http://www.douyin.com/share/user/89923222215?
http://www.douyin.com/share/user/89923222679?
http://www.douyin.com/share/user/89923223010?
http://www.douyin.com/share/user/89923223033?
http://www.douyin.com/share/user/89923223070?
http://www.douyin.com/share/user/89923224270?
http://www.douyin.com/share/user/89923224357?
http://www.douyin.com/share/user/89923224544?
http://www.douyin.com/share/user/89923224561?
http://www.douyin.com/share/user/89923224567?
http://www.douyin.com/share/user/89923224619?
http://www.douyin.com/share/user/89923226128?
http://www.douyin.com/share/user/89923226129?
http://www.douyin.com/share/user/89923226136?
http://www.douyin.com/share/user/89923226242?
http://www.douyin.com/share/user/89923226246?
http://www.douyin.com/share/user/89923226253?
http://www.douyin.com/share/user/89923226301?
http://www.douyin.com/share/user/89923226375?
http://www.douyin.com/share/user/89923226387?
http://www.douyin.com/share/user/89923226405?
http://www.douyin.com/share/user/89923226464?
http://www.douyin.com/share/user/89923226466?
http://www.douyin.com/share/user/89923226477?
http://www.douyin.com/share/user/89923226485?
http://www.douyin.com/share/user/89923226500?
http://www.douyin.com/share/user/89923226588?
http://www.douyin.com/share/user/89923226622?
http://www.douyin.com/share/user/89923227273?
http://www.douyin.com/share/user/89923227292?
http://www.douyin.com/share/user/89923227300?
http://www.douyin.com/share/user/89923227380?
http://www.douyin.com/share/user/89923227387?
http://www.douyin.com/share/user/89923227388?
http://www.douyin.com/share/user/89923227412?
http://www.douyin.com/share/user/89923227423?
http://www.douyin.com/share/user/89923227426?
http://www.douyin.com/share/user/89923227598?
http://www.douyin.com/share/user/89923227629?
http://www.douyin.com/share/user/89923227708?
http://www.douyin.com/share/user/89923228118?
http://www.douyin.com/share/user/89923228246?
http://www.douyin.com/share/user/89923228261?
http://www.douyin.com/share/user/89923228353?
http://www.douyin.com/share/user/89923228440?
http://www.douyin.com/share/user/89923229204?
http://www.douyin.com/share/user/89923229250?
http://www.douyin.com/share/user/89923230152?
http://www.douyin.com/share/user/89923230207?
http://www.douyin.com/share/user/89923230290?
http://www.douyin.com/share/user/89923231145?
http://www.douyin.com/share/user/89923231958?
http://www.douyin.com/share/user/89923232608?
http://www.douyin.com/share/user/89923232783?
http://www.douyin.com/share/user/89923233506?
http://www.douyin.com/share/user/89923233935?
http://www.douyin.com/share/user/89923234482?
http://www.douyin.com/share/user/89923234489?
http://www.douyin.com/share/user/89923234530?
http://www.douyin.com/share/user/89923234801?
http://www.douyin.com/share/user/89923235253?
http://www.douyin.com/share/user/89923235714?
http://www.douyin.com/share/user/89923235736?
http://www.douyin.com/share/user/89923235785?
http://www.douyin.com/share/user/89923236466?
http://www.douyin.com/share/user/89923236512?
http://www.douyin.com/share/user/89923236518?
http://www.douyin.com/share/user/89923236638?
http://www.douyin.com/share/user/89923237057?
http://www.douyin.com/share/user/89923237363?
http://www.douyin.com/share/user/89923237454?
http://www.douyin.com/share/user/89923237471?
http://www.douyin.com/share/user/89923237484?
http://www.douyin.com/share/user/89923237497?
http://www.douyin.com/share/user/89923238009?
http://www.douyin.com/share/user/89923238158?
http://www.douyin.com/share/user/89923238559?
http://www.douyin.com/share/user/89923238952?
http://www.douyin.com/share/user/89923239005?
http://www.douyin.com/share/user/89923239202?
http://www.douyin.com/share/user/89923239213?
http://www.douyin.com/share/user/89923239214?
http://www.douyin.com/share/user/89923239435?
http://www.douyin.com/share/user/89923240180?
http://www.douyin.com/share/user/89923240414?
http://www.douyin.com/share/user/89923240909?
http://www.douyin.com/share/user/89923241361?
http://www.douyin.com/share/user/89923241604?
http://www.douyin.com/share/user/89923241788?
http://www.douyin.com/share/user/89923243350?
http://www.douyin.com/share/user/89923244737?
http://www.douyin.com/share/user/89923249761?
http://www.douyin.com/share/user/89923251406?
http://www.douyin.com/share/user/89923251645?
http://www.douyin.com/share/user/89923251974?
http://www.douyin.com/share/user/89923252203?
http://www.douyin.com/share/user/89923252623?
http://www.douyin.com/share/user/89923253946?
http://www.douyin.com/share/user/89923254171?
http://www.douyin.com/share/user/89923254244?
http://www.douyin.com/share/user/89923254617?
http://www.douyin.com/share/user/89923254741?
http://www.douyin.com/share/user/89923256207?
http://www.douyin.com/share/user/89923256340?
http://www.douyin.com/share/user/89923256639?
http://www.douyin.com/share/user/89923256767?
http://www.douyin.com/share/user/89923257355?
http://www.douyin.com/share/user/89923257425?
http://www.douyin.com/share/user/89923257604?
http://www.douyin.com/share/user/89923258824?
http://www.douyin.com/share/user/89923259227?
http://www.douyin.com/share/user/89923259249?
http://www.douyin.com/share/user/89923259275?
http://www.douyin.com/share/user/89923259334?
http://www.douyin.com/share/user/89923259365?
http://www.douyin.com/share/user/89923259479?
http://www.douyin.com/share/user/89923259505?
http://www.douyin.com/share/user/89923259813?
http://www.douyin.com/share/user/89923259832?
http://www.douyin.com/share/user/89923259839?
http://www.douyin.com/share/user/89923259857?
http://www.douyin.com/share/user/89923259863?
http://www.douyin.com/share/user/89923259954?
http://www.douyin.com/share/user/89923260093?
http://www.douyin.com/share/user/89923260217?
http://www.douyin.com/share/user/89923261057?
http://www.douyin.com/share/user/89923261077?
http://www.douyin.com/share/user/89923261081?
http://www.douyin.com/share/user/89923261097?
http://www.douyin.com/share/user/89923261119?
http://www.douyin.com/share/user/89923261123?
http://www.douyin.com/share/user/89923261135?
http://www.douyin.com/share/user/89923261140?
http://www.douyin.com/share/user/89923261664?
http://www.douyin.com/share/user/89923261670?

**Comment by WJFQ** [comment]
老哥是如何解决的？我也出现了Aweme number 99805240/, video number 0
 但是我只是一个主页链接。

**Comment by panoslin** [comment]
你是用的安卓机分享链接吗？
试一下用苹果分享链接，安卓和苹果分享的链接不一样

**Comment by zthaa** [comment]
@panoslin 好像最近抖音分享的链接变了，但是你打开分享链接会跳转到以前的链接上。。

**Comment by panoslin** [comment]
安卓分享的链接：https://www.douyin.com/share/user/92683516474/?share_type=link
苹果分享的链接：https://www.douyin.com/share/user/92683516474?share_type=link

需要将安卓分享的链接参数前的斜杠‘/’去除，才可以正常解析页面

**Comment by zthaa** [comment]
这个到没有注意到

**Comment by huy99ls01** [comment]
i did everything you said but it's not working, still video number 0
