### ISSUE TITLE
抖音更新之后利用短链接批量下载的方法

### ISSUE THREAD

**Issue by WJFQQQ** [LoadChange/amemv-crawler#36]
以该链接为例子 [http://v.douyin.com/cE1j4/](url)

在浏览器中输入后会出现 [https://www.douyin.com/share/user/64395924642/?share_type=link](url)

这时候把
 [https://www.douyin.com/share/user/64395924642/?](url) 

去掉末尾的斜杠 `/` 变成 [https://www.douyin.com/share/user/64395924642?](url) 即可批量下载

挑战和音乐同理！

认为是抖音虽然更新但是网页中的长连接并没有太大改变，因此可以继续使用。

**Comment by WJFQQQ** [comment]
作为python初学者，看到楼主能写出这么棒的爬虫还是很惊叹的。

想学一下，然鹅大多数代码没注释看的一头包 2333

**Comment by LoadChange** [comment]
短链接的问题已经修复了

**Comment by china599** [comment]
连接打不开
