### ISSUE TITLE
process未定义

### ISSUE THREAD

**Issue by BuleTom** [loadchange/amemv-crawler#37]
拿signature过程中，出现bug，求解
process未定义
![image](https://user-images.githubusercontent.com/33994043/42121088-cbcaf252-7c59-11e8-9913-ca42674b6438.png)

**Comment by loadchange** [comment]
process是node的全局变量，我不太确定windows中执行js文件是怎样的上下文环境，如果你想了解process可以尝试在node命令行中输出process观察一下。
