### ISSUE TITLE
_signature不稳定

### ISSUE THREAD

**Issue by chaopengz** [loadchange/amemv-crawler#39]
七月二号更新算法后，用新的fuck-byted-acrawler.js拿到的_signature有时能用有时失效，这回确定所用的headers 和amemv-video-ripper.py中的header一致，请问可能是什么原因呢？Thanks~

**Comment by zhu-jz** [comment]
今天又增加了_dytk参数

**Comment by fullvip** [comment]
今天我也看到了，这个现在我也在分析，研究三天了
