### ISSUE TITLE
大大帮忙看一看这是什么原因

### ISSUE THREAD

**Issue by hzc54188** [LoadChange/amemv-crawler#4]
![qq](https://user-images.githubusercontent.com/24639554/38363526-92dc5bec-3907-11e8-9c12-6140910ad192.png)

**Comment by LoadChange** [comment]
不好意思，刚看到，这个是因为抖音下掉了一个接口导致的，没办法，我再找找看吧，修好回你😄

**Comment by hzc54188** [comment]
@LoadChange 爱你哟

**Comment by LoadChange** [comment]
可以了，接口还是在的，只是下掉了PC的服务，所以验证了是否是手机，ua中增加一条，又可以跑了✌️

**Comment by LoadChange** [comment]
可以了，接口还是在的，只是下掉了PC的服务，所以验证了是否是手机，ua中增加一条，又可以跑了✌️

**Comment by LoadChange** [comment]
可以了，接口还是在的，只是下掉了PC的服务，所以验证了是否是手机，ua中增加一条，又可以跑了✌️

**Comment by LoadChange** [comment]
可以更新了，接口还在，只是停掉了PC服务，在ua中伪装成手机就能跑起来了✌️

**Comment by hzc54188** [comment]
@LoadChange 这真是最美的期待了https://www.douyin.com/share/music/6512693853051751182
