### ISSUE TITLE
視頻分享链接

### ISSUE THREAD

**Issue by steven7851** [loadchange/amemv-crawler#41]
https://www.douyin.com/share/video/6557825773007277319/?mid=6557826301539912456
现在的视频分享链接都需要 mid 这个参数才能开启，但 aweme/post 返回的 share_url 是不带这个参数的，请问有没有不用抖音分享就能取得 mid 的方式？我知道与这个 project 无关，但是找不到地方发问。 。

**Comment by loadchange** [comment]
应该是不行的

**Comment by steven7851** [comment]
好吧，感谢回答TT
