### ISSUE TITLE
大大能增加按音乐下载的方法吗 爱你哟

### ISSUE THREAD

**Issue by hzc54188** [LoadChange/amemv-crawler#5]
您看这些优质却不火的小姐姐和小哥哥也很迷人的啊...
【https://www.baidu.com/s?wd=site:www.douyin.com 原声&rsv_spt=1&rsv_iqid=0xd18eb8e00001789c&issp=1&f=8&rsv_bp=1&rsv_idx=2&ie=utf-8&rqlang=cn&tn=baiduhome_pg&rsv_enter=1&oq=site:www.douyin.com&inputT=3571&rsv_t=2159rBGYGurBOOLUugTfccSGWHwY2jIWQGxIgSygjKHtJeJb9nu2T7+AZjaO/Ei0seKm&rsv_sug3=29&rsv_pq=ce3f516b0000f181&rsv_sug2=0&rsv_sug4=3936】

**Comment by LoadChange** [comment]
如果你想下载按音乐去下载，请在 user-number.txt 文件中添加 @关键词
