### ISSUE TITLE
效果超赞！👍👍👍 可否加一个不下载用户收藏(Favorite)的参数

### ISSUE THREAD

**Issue by NJCCJohnWason** [loadchange/amemv-crawler#50]
看到这个repo后第一时间下载下来配置并使用，效果很好，没有水印，速度也很快，作者辛苦！
同时发现一个问题：一个用户可能自己的作品不多，但是他喜欢的作品超多（比如我2333），就导致爬虫工作的大部分时间都是在下用户的收藏。但是很多时候我们只需要该作者的作品就够了。
所以是否可以加一个不下载用户收藏的功能，比如 命令类似这样：python amemv-video-ripper.py -nofavorite 
最后再次感谢作者的付出，请作者收下我们的膝盖 ^_^

**Comment by laughmaker** [comment]
这个看一看代码，注册掉相关的就好了

**Comment by NJCCJohnWason** [comment]
已经注释掉了，可以正常使用，感谢。

**Comment by loadchange** [comment]
✨✨@NJCCJohnWason 试一下😀

**Comment by NJCCJohnWason** [comment]
好的 多谢
