### ISSUE TITLE
fuck-byted-acrawler.js 又更新了 现在signature无效

### ISSUE THREAD

**Issue by gxqc** [loadchange/amemv-crawler#56]
还请更新fuck-byted-acrawler.js

**Comment by fallenlord** [comment]
看到好像现在的接口中都是mas, as, ts这样，没有看到signature以及README.md中提及的cp。是老的接口才使用的吗？

**Comment by namespacegit** [comment]
测试了下，应该还可以用

**Comment by gxqc** [comment]
tac这个参数都没有 怎么会好用呢 而且抖音几个js文件里的算法明显不一样了

**Comment by fallenlord** [comment]
@gxqc 抖音有哪个页面里有播放、点赞、评论这些数据吗？

**Comment by hzc54188** [comment]
失效了这是一个遗憾

**Comment by loadchange** [comment]
@gxqc 在哪里有__tac__这个参数？
