### ISSUE TITLE
请问大神， 如果我想下载单个视频，该如何改？谢谢

### ISSUE THREAD

**Issue by toneytang** [loadchange/amemv-crawler#59]
请问大神， 如果我想下载单个视频，该如何改？谢谢

**Comment by loadchange** [comment]
`chrome` 调试就可以找到视频链接了

**Comment by toneytang** [comment]
![_20180910142720](https://user-images.githubusercontent.com/21031528/45273214-a7d4b880-b505-11e8-8e8b-41c244fc4a25.png)
代码中的aweme是不是就是视频链接？


通过chrome调试，我已经找到下面的两个链接，不知道怎么用。。
https://www.iesdouyin.com/share/video/6597280517584850184
https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v0200f1b0000be73v8kr08mfp0n6g6qg&line=0

**Comment by loadchange** [comment]
<img width="971" alt="1x20180910103408" src="https://user-images.githubusercontent.com/10842824/45273428-4e5c9180-b4e5-11e8-883b-91dcaa9dcffa.png">

https://aweme.snssdk.com/aweme/v1/playwm/?video_id=v0300f080000beafdlabc5oi3gg5baa0&line=0

**Comment by toneytang** [comment]
这个链接已经拿到了。但不知道在代码里面什么地方用。。。

**Comment by toneytang** [comment]
self._join_download_queue(aweme, target_folder)
这个应该是最底一层的下载方法。

但不知道怎么得到aweme传递给它。

**Comment by loadchange** [comment]
现在不支持下载单个的😁

**Comment by liujian18** [comment]
无水印的原理是什么呢？
