### ISSUE TITLE
下载有水印

### ISSUE THREAD

**Issue by lyj9768** [loadchange/amemv-crawler#66]
此时此刻，下载的有水印！！！

**Comment by loadchange** [comment]
是的，视频链接策略好像发生了改变，暂时降级到有水印的版本了

**Comment by AppSign** [comment]
> 此时此刻，下载的有水印！！！

可以尝试使用，http://tools.appsign.vip/，获取视频下载地址，使用python或者迅雷下载(下载后需要重命名)。目前仍为无水印版本。

如果熟悉python开发的话，可以参考https://github.com/AppSign/douyin，自行加签爬取视频

**Comment by AppSign** [comment]
> 是的，视频链接策略好像发生了改变，暂时降级到有水印的版本了

建议可以增加[AppSign douyin](https://github.com/AppSign/douyin) app加签方式，免费提供app的 as mas 加签，爬虫方面可以获取更多的信息。 用户依据参数选择对应的爬虫加签方式。

**Comment by steven7851** [comment]
https://github.com/loadchange/amemv-crawler/blob/a96fe62df2070988ffeae1b32f9926568ce5bea9/amemv-video-ripper.py#L171
修改这里可获取无水印连接
```python
playAddr['url_list'][0].replace('playwm', 'play')
```
@AppSign 永久免费?

**Comment by loadchange** [comment]
@AppSign 感谢提供了一个新的方式，我会尽快尝试这个方法的👍

**Comment by AppSign** [comment]
> [amemv-crawler/amemv-video-ripper.py](https://github.com/loadchange/amemv-crawler/blob/a96fe62df2070988ffeae1b32f9926568ce5bea9/amemv-video-ripper.py#L171)
> 
> Line 171 in [a96fe62](/loadchange/amemv-crawler/commit/a96fe62df2070988ffeae1b32f9926568ce5bea9)
> 
>  self.queue.put(('video', playAddr['uri'], playAddr['url_list'][0], target_folder)) 
> 
> 修改这里可获取无水印连接
> ```python
> playAddr['url_list'][0].replace('playwm', 'play')
> ```
> 
> @AppSign 你这个服务是永久免费的吗? 还是未来有收费可能?

抖音Sign目前不会收费，将来也不会收费。正常调用量当前服务器没有问题，如果调用量特别大的而且需要保证稳定性入门级服务器扛不了，可以联系单独开一个服务器。
以后支持更多的APP签名，不能保证全部免费。

**Comment by za123** [comment]
将楼主项目与AppSign douyin项目集合，目前无水印
https://github.com/za123/TIKtok

**Comment by loadchange** [comment]
尝试了 @AppSign 的方法，效果不是很理想，增加一个异步会增加很多意外，决定还是不要使用这种方式了；还是感谢各位的参与了，还有 @za123 已经有自己的实现 👍，想通过 @AppSign 的服务下载的可以尝试 @za123  的项目。

目前已经解决了水印的问题，可以正常下载无水印视频了~
