### ISSUE TITLE
Music and some challenge cannot be downloaded

### ISSUE THREAD

**Issue by umhyper** [loadchange/amemv-crawler#70]
Hi there, 

This is absolutely a great work!
However, I copy some MUSIC share link to share-url.txt, it just did not work.

It shows "There's no video in music XXXXXX" .

Here's the share link, 

https://t.tiktok.com/i18n/share/music/6601007846454725377?u_code=cm5g8g76bl4700&utm_source=copy&app=tiktok&iid=6608848021050623746&utm_campaign=client_share&utm_medium=ios&tt_from=copy&user_id=6536000640706822145

Could you help me figure this out? 

Thanks in advance!

**Comment by loadchange** [comment]
Sorry, this is an imperfect solution. Currently, access to TikTok is prohibited in China, only video with watermark can be downloaded for you. I will keep this problem and try to solve the problem of not being able to access TikTok. If you can help me, I would really appreciate it. You can find the data source of TikTok waterless version for me through the agent tool.
