### ISSUE TITLE
抖音不能成功下载

### ISSUE THREAD

**Issue by yihuali** [loadchange/amemv-crawler#73]
pip install -r requirements.txt 提示说已经在Anaconda里有了更高版本，因此导致不能正常下载吗（提示说下载完成了，实际一个都没下载过来。）？

Requirement already satisfied: requests>=2.10.0 in d:\anaconda\lib\site-packages (from -r requirements.txt (line 1)) (2.19.1)
Requirement already satisfied: six in d:\anaconda\lib\site-packages (from -r requirements.txt (line 2)) (1.11.0)
Requirement already satisfied: PySocks>=1.5.6 in d:\anaconda\lib\site-packages (from -r requirements.txt (line 3)) (1.6.8)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in d:\anaconda\lib\site-packages (from requests>=2.10.0->-r requirements.txt (line 1)) (1.23)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda\lib\site-packages (from requests>=2.10.0->-r requirements.txt (line 1)) (2018.8.24)
Requirement already satisfied: idna<2.8,>=2.5 in d:\anaconda\lib\site-packages (from requests>=2.10.0->-r requirements.txt (line 1)) (2.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in d:\anaconda\lib\site-packages (from requests>=2.10.0->-r requirements.txt (line 1)) (3.0.4)

**Comment by NinjaMoon** [comment]
我也遇到同样的问题看来是个BUG

**Comment by eightrivers** [comment]
遇到同样的问题。

环境：win10 x64 中文 最新补丁安装， Anaconda附带的Python3.6.5。

执行cmd：python amemv-video-ripper.py  http://v.douyin.com/R1v4j9

console输出：
============================================
$ python amemv-video-ripper.py  http://v.douyin.com/R1v4j9

Aweme number 99082530679, video number 75



Finish Downloading All the videos from 99082530679
============================================

执行过程无报错，目录也创建了，但创建的目录里除了名为favorite的子目录之外面没有任何文件。

**Comment by one-smiling** [comment]
@eightrivers              
把198行
```
 if aweme['hostname'] == 't.tiktok.com':
```
改成
```
 if aweme.get('hostname') == 't.tiktok.com':
```
就可以了

**Comment by eightrivers** [comment]
@one-smiling 改过之后问题解决，非常感谢！
