### ISSUE TITLE
如果想要获取用户的音乐信息，有什么好的爬取思路呢？

### ISSUE THREAD

**Issue by LukeHe** [loadchange/amemv-crawler#75]

**Comment by loadchange** [comment]
具体什么信息呢，目前的思路可以获取的信息还是很多的，只是没有做这些内容的保存

**Comment by LukeHe** [comment]
> 具体什么信息呢，目前的思路可以获取的信息还是很多的，只是没有做这些内容的保存
有个aweme变量，主要是从这里面获取信息，但是现在好像没有音乐信息了，music是一个空字典，主要是想获取选取的用户的上传视频的音乐信息，比如音乐名称，音乐播放地址等等。

**Comment by LukeHe** [comment]
@loadchange 但是手机app上是可以呈现出音乐信息的，我觉得应该可以爬取的吧

**Comment by loadchange** [comment]
> @loadchange 但是手机app上是可以呈现出音乐信息的，我觉得应该可以爬取的吧

这个要用客户端api，需要签名，h5接口没有合适的
