### ISSUE TITLE
只能下载favorite，不能下载用户视频

### ISSUE THREAD

**Issue by eightrivers** [loadchange/amemv-crawler#76]
试了好几个用户账号，都存在这个问题：只能下载到某个用户的favorite视频，而不能下载到此用户自己的视频。

例如以下几个用户都存在此问题：

- http://v.douyin.com/R81gUt/
- http://v.douyin.com/RRvUWW/
- http://v.douyin.com/R8JWk3/

而有少数个别用户是可以又下载到favorite又下载到自己的视频的，例如：http://v.douyin.com/RRv9jX/ 

另外，下载到的favorite的数量好像也和抖音上的数量不一样，一般下载的数量会比抖音上的少一些。

麻烦请看看是什么问题，谢谢！

**Comment by loadchange** [comment]
1、没有下载用户视频

一个正常的用户视频列表的响应差不多长这样
![image](https://user-images.githubusercontent.com/10842824/47264099-ebc5cf00-d541-11e8-991a-5fe6e6f84afa.png)
其中很关键的一个字段`has_more: 1` 表示还有下一页， 可是有的时候我们却拿到了 

`{"status_code": 0, "has_more": true, "aweme_list": []}`

这样的结果，很莫名其妙，我的判断是 `has_more == 1` 时继续，这样看来就有问题了，它会导致提前退出循环，修改的方案是暂时把 `== 1 ` 去掉吧。但是 `has_more: true` ，同时 `aweme_list:[]` 也是非常诡异的，我怀疑这个可能是抖音后端的一个bug

2、下载数量与用户数量不一致
这个问题好像是抖音的bug，下面是我浏览器模拟拉用户全部视频的截图

作品数：74

第一页： 20个

![image](https://user-images.githubusercontent.com/10842824/47264127-c5ecfa00-d542-11e8-9e4e-6841fbaa0702.png)

第二页： 20个

![image](https://user-images.githubusercontent.com/10842824/47264138-f03eb780-d542-11e8-8673-b7b83fe15220.png)

第三页：20个

![image](https://user-images.githubusercontent.com/10842824/47264145-fd5ba680-d542-11e8-9b83-144838007372.png)

第四页：10个

![image](https://user-images.githubusercontent.com/10842824/47264154-1ebc9280-d543-11e8-841c-6beaf8ccd026.png)

第四页结果 `has_more: 0` 可见已经没有更多，`70??  74??  ????`。

**Comment by eightrivers** [comment]
@loadchange， 谢谢详尽的回复啊！ 

所以这里应该是抖音的问题了。

用其他工具也偶尔有类似的问题，不过更多的是下载到一个视频打开后说原视频找不到了。 

https://app886.cn/douyin_video 这个工具相对好像稳定点，可以供你们分析时参考，再次感谢！
