### ISSUE TITLE
tiktok下载失败

### ISSUE THREAD

**Issue by 23233** [loadchange/amemv-crawler#92]
##  下载生成url 
```
http://api.tiktokv.com/aweme/v1/play/?video_id=v07025bc0000bg1sv7874qggpq27jefg&line=0&ratio=720p&media_type=4&vr_type=0&test_cdn=None&improve_bitrate=0&version_code=1.7.2&language=en&app_name=trill&vid=D7B3981F-DD46-45A1-A97E-428B90096C3E&app_version=1.7.4&device_id=661978555206485964289&channel=App Store&mcc_mnc=&tz_offset=28800
```

## 直接访问返回 

- {"status_code":0,"status_msg":""}

## 网址检验 
[https://t.tiktok.com/i18n/share/video/6630371435921542401](https://t.tiktok.com/i18n/share/video/6630371435921542401)

## 请求大神 tiktok如何下载/获取无水印版？ 谢谢

**Comment by steven7851** [comment]
API 已变更，这样即可下载
`https://api2.musical.ly/aweme/v1/play/?video_id=v07025bc0000bg1sv7874qggpq27jefg&line=0&ratio=720p&media_type=4&vr_type=0&test_cdn=None&improve_bitrate=0`

**Comment by loadchange** [comment]
这个是单视频的分享链接吧

**Comment by loadchange** [comment]
不支持单视频的，单视频如果只是需要一个无水印的视频，直接用chrome查看源码就可以了
