### ISSUE TITLE
是我环境没配好吗？mac

### ISSUE THREAD

**Issue by yovenny** [loadchange/amemv-crawler#98]
python2.7
MacBook-Pro:amemv-crawler skyArraon$ python amemv-video-ripper.py http://v.douyin.com/L1jMvr/
Traceback (most recent call last):
  File "amemv-video-ripper.py", line 6, in <module>
    import urllib.parse
ImportError: No module named parse

**Comment by yovenny** [comment]
先切换pip3看看

**Comment by HarryYC** [comment]
https://stackoverflow.com/questions/13967428/importerror-no-module-named-six

**Comment by yovenny** [comment]
好的
